services:
  postgres:
    image: postgres:15-alpine
    container_name: portfolio-db
    environment:
      POSTGRES_DB: portfoliotracker
      POSTGRES_USER: portfolio_user
      POSTGRES_PASSWORD: portfolio_pass
    ports: ["5432:5432"]
    volumes: [postgres_data:/var/lib/postgresql/data]

  backend:
    image: openjdk:17
    container_name: portfolio-backend
    working_dir: /app
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/portfoliotracker
      SPRING_DATASOURCE_USERNAME: portfolio_user
      SPRING_DATASOURCE_PASSWORD: portfolio_pass
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      JWT_SECRET: your-jwt-secret-key-12345
    ports: ["8080:8080"]
    volumes:
      - ./tracker:/app
    command: >
      sh -c "
        cd /app &&
        mvn clean package -DskipTests &&
        java -jar target/*.jar
      "
    depends_on:
      - postgres

  frontend:
    image: node:18
    container_name: portfolio-frontend
    working_dir: /app
    ports: ["5173:5173"]
    volumes:
      - ./client:/app
      - /app/node_modules
    command: npm run dev -- --host
    depends_on:
      - backend

volumes:
  postgres_data: